---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fly.
--- DateTime: 2026/4/15 15:50
---
--1参数列表
--1.1优惠券id
local voucherId = ARGV[1]
--1.2用户id
local userId = ARGV[2]
--2数据key
--2.1库存key
local stockKey = "seckill:stock:" .. voucherId
--2.2订单key
local orderKey = "seckill:order:" .. userId
--3脚本业务
--3.1判断库存是否充足
if (tonumber(redis.call("get", stockKey)) <= 0) then
    --3.2库存不足
    return 1
end
--3.3判断用户是否重复下单
if (redis.call("sismember", orderKey, userId) == 1) then
    --3.4用户重复下单
    return 2
end
--3.4扣减库存
redis.call("incrby", stockKey, -1)
--3.5下单（保存用户）
redis.call("sadd", orderKey, userId)
return 0
